#!/bin/bash
#
# this script should not be run directly,
# instead you need to source it from your .bashrc,
# by adding this line:
#   . ~/jump/jump.sh
#

function jump() {
  # output=$(go run src/jump.go $1)
  output=$(jump-walker $1)
  cd $output
  ls -l
}
