#!/bin/bash
#
# this script should not be run directly,
# instead you need to source it from your .bashrc,
# by adding this line:
#   . ~/bin/myprog.sh
#

function jump() {
  output=$(go run src/jump.go $1)
  cd $output
}